name: Lint

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - master
jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Setup Ruby 3.0.1
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.1
      - name: Install Rubocop
        run: gem install rubocop
      - name: Run Rubocop
        run: rubocop -P